### ISSUE TITLE
Solar tab "slots" can't be covered/touched by structure. Also, change in hole locations.

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-structure#19]
The 4 narrow (~ 1 mm) vertical slots in the Solar module PCB is where the tabs from the solar modules come through from the front side of the board, get folded 90 degrees, and then get soldered to the PCB at the square footprints located by each slot. The tabs are relatively thick (~ 0.2 mm) tinned copper strips. As currently drawn in:

https://github.com/oresat/oresat-structure/blob/master/Solar/Solar_board_drawing.PDF

The structure "keep out" area partially covers the slots. It can't do that. Only the bare PCB surface is allowed to touch the PCB. My only suggestion is to make the struts on top and bottom thinner so that they avoid the tab slots altogether by some margin (e.g. ~ 0.5 mm).

Finally, the fastener holes in the solar modules aren't centered in the structure's width... should we do that?

**Comment by Joedang** [comment]
The aforementioned slots now have (IIRC) 0.25 mm and 0.75 mm clearances around them on the peripheral and inner ends, respectively. The screw holes are now symmetric under reflection around a Z plane on the center of the board's outline.
