### ISSUE TITLE
Move backplane mounting holes off of the solar panel mounting holes

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-structure#21]
We're moving them into separate holes so it's easier to bolt together, we don't have to have very short screws, and we won't have little air pockets between the bolts.

**Comment by Joedang** [comment]
Done. The backplane mounting holes now appear between the solar board mounting holes, and the stand-off holes are on the next strut intersection over from the solar board holes. (This will show up after #23 is closed and I merge from `dev_joe`.)

Someone is going to get really good at tapping small holes...
