### ISSUE TITLE
Update backplane with new 26 pin connector 

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-structure#23]
Replace the 40 pin SMT Har-Flex connector with the new 26 pin through-hole connector, and move it from the "right" of the backplane board to the center of the board. The new connector is the Harting 1521026X4XXXXX. This makes us very sad because we can use any thing less than 38 pins, but the jerks only make he 26 pin version. STEP file can be found [here](https://b2b.harting.com/ebusiness/en_us/itemdocument/15210262401000/STEP).

**Comment by Joedang** [comment]
Nope, we're using the 40 pin Tiger Eye connector mentioned in #24.
