### ISSUE TITLE
Pick the actual damn connector

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-structure#24]
Choose a new connector that is < 29.5 mm wide and has all of the good properties.

**Comment by Joedang** [comment]
We're using the Tiger Eye TFM_120_01_L_D_RA and SFM_120_01_L_D_LC. They're close to that 29.5 mm size that's dictated by the screws that stabilize the backplane. However, they're always offset from the center of the screws, so it's NBD.

![image](https://user-images.githubusercontent.com/16861664/36962879-1b4c0d30-2006-11e8-8f3c-3526ca79ebfb.png)

![image](https://user-images.githubusercontent.com/16861664/36963011-7fb1cc10-2006-11e8-9ff4-c6bad43e5457.png)
