### ISSUE TITLE
Rename all the things

### ISSUE THREAD

**Issue by Joedang** [oresat/oresat-structure#25]
A bunch of the names of things don't really follow the naming convention in the [contribution guide](https://github.com/oresat/oresat-structure/blob/master/.github/CONTRIBUTING.md) or aren't really clear. They should be renamed.

## Things with names that should be changed
- [ ] doc/CubesatDesignSpec.pdf -> kill
- [ ] drawings -> merge into appropriate directories
- [ ] hardware -> merge into COTS
- [ ] head-tail -> Zneg_endcard and Zpos_endcap
- [ ] Zneg -> Zneg_endcap
- [ ] Zpos -> Zpos_endcap
- [ ] inhibit -> InhibitCard
- [ ] keepout -> volumeKeepout
- [ ] rack -> frames
- [ ] CardModules -> Camera

When done, open the top level assembly, point it to the new locations, save everything, and push the updated references. (Also, inform people that there are going to be a bunch of changes to both locations and CAD files.)

**Comment by andrewgreenberg** [comment]
All the things were renamed! So much way better.
