### ISSUE TITLE
Fix solar connector and verify PCB against DXF

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-structure#26]
In the current CAD, the Alta 5 cell module has four slots the tabs go through. The top two slots are underneath the Aluminum frame, so I shifted the entire module down (slots and all) by 0.5 mm.

Please update the CAD and drawings of the solar panels.

**Comment by andrewgreenberg** [comment]
Joe: Can you please verify this?

**Comment by andrewgreenberg** [comment]
Probably done, but we should really verify this.

**Comment by andrewgreenberg** [comment]
OK ignore all the stuff above: The solar connectors are wrong. Change to the through hole versions, and then verify the PCB outlines and BSTOP layers against the new DXF from Jeremy.

**Comment by jalouke** [comment]
The drawing is updated to include the center location of the connector. The change is on the "footprints" page.

**Comment by andrewgreenberg** [comment]
Done!
