### ISSUE TITLE
Revise Frame Drawings

### ISSUE THREAD

**Issue by Joedang** [oresat/oresat-structure#31]
The +/-X frame drawings are missing the Z width of screw pillars. The drawings should also be distributed over multiple pages (US Letter size), because they're kind of hard to read right now.

**Comment by Joedang** [comment]
At this point, the drawings should probably just be redone from scratch. I don't think the originals had anything to do with the lattice on the outside. They certainly don't include the stuff for the spring pins or backplane standoffs.

While we're at it, we should add a statement of which license we're using.

**Comment by andrewgreenberg** [comment]
They were redone, closing this old issue.
