### ISSUE TITLE
Research adhesives and epoxies

### ISSUE THREAD

**Issue by Joedang** [oresat/oresat-structure#35]
Collect information on different adhesives and epoxies. We care about ease/safety of application, outgassing, thermal/electrical conductivity, bond strength/compatibility, elastic modulus, working temperature, and typical applications. We have a few different use cases to fill. 

We are going to thermal-epoxy the solar panels to their boards and the boards to the structure. So, we need something with high thermal conductivity. It should probably also have a low elastic modulus and high bond strength with gold and aluminum. It's probably going to experience a fair amount of thermal strain, and we don't want it to crack.

Each card is probably going to get a silastic coating.

We were originally planning on using Locktite for fasteners, but apparently nitronic locking helicoils are sufficient.

We also probably need a general-purpose epoxy for large components and connections.

Epibond 123 and Locktite were suggested. Space-rated epoxy is a thing.

**Comment by jalouke** [comment]
Have you looked into using the Torr Seal I sent Andrew last year? It is
meant to be a low off gassing epoxy for high vacuum applications. I may
have more that is getting ready to "expire" soon.
