### ISSUE TITLE
Card notches don't line up with backplane screws

### ISSUE THREAD

**Issue by Joedang** [oresat/oresat-structure#37]
![image](https://user-images.githubusercontent.com/16861664/49345473-3acf4b80-f63a-11e8-98ba-80b9aed85e6d.png)

The backplane has a bunch of screws that hold it to the -X frame. Correspondingly, the cards have notches to avoid hitting these screws. Currently, those notches are not misaligned with the screws. It's not enough to break things, but they should be lined up.

**Comment by andrewgreenberg** [comment]
Already fixed!
