### ISSUE TITLE
Deepen the spring pin holes on the ends of the rails

### ISSUE THREAD

**Issue by Joedang** [oresat/oresat-structure#38]
With the presently specified hole depths, the spring pins on the -Z ends of the rails don't sit deep enough. When machined, there was some significant variation in how deep the threads/holes went. So, the threaded case of the spring pin sits out too far. Just deepen the holes and extend that chunk of aluminum to make sure it doesn't break through. (Actually, should we be venting that hole?)

**Comment by IanZabel** [comment]
I would personally only recommend venting the hole if it is a press fit or excessively deep (like one order-of-magnitude greater than diameter). This one may not warrant it.

**Comment by andrewgreenberg** [comment]
This was just done. Don't need to vent, because the spring pins themselves have a hollow core which allows them to vent.
