### ISSUE TITLE
Holes for the frame's M2.5 socket head bolts to be fixed

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-structure#41]
The counterbored holes in the +/-X frames  for the M2.5 socket head bolts is current countersunk. Change to counter board, and bring the head of the bolt towards the surface of the rail in order to add more material under the head - it's unnecessarily tight under the head.

This will also require those M2.5 bolts to get longer.

**Comment by catiespivey** [comment]
reduced head clearance by 2mm and changed screw length from 8mm to 10mm and updated the drawings to reflect this change
