### ISSUE TITLE
Match +/-Y frame tabs with +X tabs, move top and bottom tabs

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-structure#46]
While working with Oleg on placing the battery cards, we realized that the "tabs" on the +/-Y frames (the tabs that have the M2.5 helicoils in them) are too large in the Z axis. They scrape the cards that are above and below them. The tabs on the +X frame seems to be sized correctly, so you could just match that. There are 8 tabs all together, and I think doing this on the "inner" 4 tabs will work.

There's an issue for the outer four tabs, however: they also have alignment pins in them. I think it might work if we move these outer tabs to just below the end caps - if we did that, they could touch the end caps, and thus have room for the pins. The sides that touch the end cards, however, still do need to be cut back.

This all probably needs a drawing, so let's chat on Thu/Fri. It also might be weirdly complicated, so I'm CC'ing Ryan on this one.

**Comment by catiespivey** [comment]
I think this is a non issue now?
