### ISSUE TITLE
Add an upper, and maybe lower slot, to the RW assembly area to the 1.5U, 2U, and 3U frames

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-structure#70]
Not everyone will use the RWs/MTs, we should have as many slots there as possible. Certainly add the obvious one at the top of the assembly, but I'm unclear if adding another slot at the bottom (above the ACS card) will screw things up.

**Comment by marvinlinn** [comment]
Checked and solution determined that extra slot would not be useful. Instead, reaction wheel-less designs were made.
